Личный проект: хрустящий CRUD
htmlacademy-nodejs/1708501-typoteka-3 pull request #11
Opened 2021-09-27 21:25 UTC by YoginAlex

2021-09-28 05:16 UTC, what1s1ove requested changes

2021-09-28 05:16 UTC, what1s1ove commented on package.json
> +    "nanoid": "^3.1.28",
версии пакетов должны быть зафиксированы

2021-09-28 05:16 UTC, what1s1ove commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
```suggestion
  if (data !== null) {
    return data;
  }

    const fileContent = await fs.readFile(MOCK_FILE_PATH);
    data = JSON.parse(fileContent);

  return data;
```
функция итак async, лишние обертки никчесму

2021-09-28 10:14 UTC, YoginAlex commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
Поясню. Код брал из https://up.htmlacademy.ru/nodejs/3/book/4.13 раздел Разработка API. 
Единственное, что мы вызываем её асинхронно в итоге `const mockData = await getMockData();`, а значит она должна всегда возвращать Promise. Вроде так...

2021-09-28 10:34 UTC, what1s1ove commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
Асинхронная функция всегда возвращает промисс

2021-09-28 10:44 UTC, YoginAlex commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
Да, конечно. Я про блоки выше и ниже readFile
```
if (data !== null) {
    return data;
  }
```
и 
```
return data;
```

Хотя, попробовал сейчас, нормально отрабатывает. Спасибо!


Но try/catch я бы оставил, для отлова падения JSON.parse(), что, к сожалению, не является редкостью.

2021-09-28 10:53 UTC, what1s1ove commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
Так а какой смысл от этого трайкеча? ты кидаешь эту ошибку дальше. Ты же её не обрабатываешь. Тоесть от него сейчас пользы 0. Такое же поведение будет без этого.

2021-09-28 10:59 UTC, YoginAlex commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
Ну тоже верно. Спасибо!
Пример в учебники немного смущает

2021-09-28 11:01 UTC, what1s1ove commented on src/service/lib/get-mock-data.js
> +  return Promise.resolve(data);
Пример в учебнике это эталон (просто пример). Там не обязательно то, как должно быть 100%. Нужно тоже думать, так сказать 🙂

2021-09-29 07:42 UTC, what1s1ove approved these changes

2021-09-29 07:42 UTC, merged